In [3]:
import numpy as np
test = np.zeros((50, 1, 372))
train = np.zeros((500, 372))
d = (test-train) * (test-train)
print(np.shape(d))
print(np.shape(np.sum(d, axis=2)))

(50, 500, 372)
(50, 500)


In [2]:
import sys
print(sys.version)

3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]


In [5]:
import numpy as np
test = np.zeros((500, 3072))
train = np.zeros((5000, 3072))
# dd = test*test + train*train -2 * test * train 
dot = np.dot(test, train.T)
tr = np.sum(train*train, axis =1)
te = np.sum(test*test, axis =1)
dd = tr + np.reshape(te, (500, 1)) - 2*dot
# dd = np.sum(np.reshape(test*test, (500, 1, 3072)) + (train*train), axis=2)-2*dot
print(np.shape(dd))

(500, 5000)


In [23]:
import numpy as np
scores = np.array(range(-50,50)).reshape(10, 10)
correct = np.array(range(10)).reshape(10, 1)
print(scores, correct)
diff = scores -  correct + 1
print(diff)
diff = np.maximum(diff, 0)

diff

[[-50 -49 -48 -47 -46 -45 -44 -43 -42 -41]
 [-40 -39 -38 -37 -36 -35 -34 -33 -32 -31]
 [-30 -29 -28 -27 -26 -25 -24 -23 -22 -21]
 [-20 -19 -18 -17 -16 -15 -14 -13 -12 -11]
 [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
 [  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]] [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[-49 -48 -47 -46 -45 -44 -43 -42 -41 -40]
 [-40 -39 -38 -37 -36 -35 -34 -33 -32 -31]
 [-31 -30 -29 -28 -27 -26 -25 -24 -23 -22]
 [-22 -21 -20 -19 -18 -17 -16 -15 -14 -13]
 [-13 -12 -11 -10  -9  -8  -7  -6  -5  -4]
 [ -4  -3  -2  -1   0   1   2   3   4   5]
 [  5   6   7   8   9  10  11  12  13  14]
 [ 14  15  16  17  18  19  20  21  22  23]
 [ 23  24  25  26  27  28  29  30  31  32]
 [ 32  33  34  35  36  37  38  39  40  41]]


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41]])

In [24]:
diff[np.arange(diff.shape[0]),scores] = 0
diff

IndexError: index -50 is out of bounds for axis 1 with size 10

In [105]:
scores.reshape(scores.shape[0],-1)
# (scores)
np.arange(10).T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
scores[:,:]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [124]:
scores.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
scores.reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [13]:
import numpy as np
null = np.zeros([10, 5])
y = np.array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])
print(null)
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4 0 1 2 3 4]


In [18]:
null[np.arange(null.shape[0]), y.flatten()] = sorted([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])
null

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 2.],
       [2., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

# SGD

In [50]:
import numpy as np
x = np.array([[[1, 2], [3, 4], [0, 1]], [[5,6], [7, 8], [1, 0]], [[1, 2], [3, 4], [0, 1]], [[1, 2], [3, 4], [0, 1]]])
print(x.shape)
idx = np.random.choice(x.shape[0], 3)
print(idx)
x[idx].shape

(4, 3, 2)
[2 0 0]


(3, 3, 2)

In [59]:
a = np.array([[1, 3, 2], [9, 5, 4], [0, 1, 6]])
np.argsort(a)[:, -1]

array([[0, 2, 1],
       [2, 1, 0],
       [0, 1, 2]])